### PR TITLE
WIP: Fix circleci

### PR DESCRIPTION
**Pull request by portaloffreedom**
Trying to fix circleci

### CODE REVIEW

**Comment by DaanZ** [comment]
CI build works now, but it maybe uses some older building instructions, thereby blocking the build.

**Review by DaanZ — COMMENTED** [review]
Seems good so far, is the testing part of the fixing Circle CI?

**Comment by portaloffreedom** [comment]
Build now works, tests fail because we need at least python 3.7 (https://docs.python.org/3/library/__future__.html)
We need to update the base image of `cigroup/gazebo:gazebo10-revolve` to a more updated ubuntu version (with a newer version of python).

We are now using `ubuntu:xenial 16.04` as a base. Looking at https://distrowatch.com/table.php?distribution=ubuntu I sugget we update at the latest LTS: `ubuntu:focal 20.04` which has python 3.8

**Comment by portaloffreedom** [comment]
maybe we should merge this one and create a separate merge request for fixing the tests, yes

**Review by DaanZ — APPROVED** [review]

**Pull request merged**
